
[profile.default]
solc_version = '0.8.25'
src = 'src'
out = 'out'
libs = ['lib']
via_ir = true
# fuzz_runs = 500
# optimizer = true
# optimizer_runs = 10_000_000

# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
# [profile.default.optimizer_details]
# constantOptimizer = true
# yul = true

# [profile.default.optimizer_details.yulDetails]
# stackAllocation = true
bytecode_hash = "none"
deny_warnings = false
cbor_metadata = false
sparse_mode = false
build_info = true
verbosity = 3

[profile.dependencies]
solmate = { git = "https://github.com/Rari-Capital/solmate" }
forge-std = { git = "https://github.com/foundry-rs/forge-std" }
LayerZero-v2 = { git = "https://github.com/LayerZero-Labs/" }

remappings = [ 
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/'
]
